export const createServerPackage = (name: string) => {
    return (`{
"name": "${name}-server",
"version": "0.1.0",
"main": "server.js",
"license": "MIT",
"dependencies": {
    "@types/faker": "^5.1.0",
    "@types/graphql": "^14.5.0",
    "@types/helmet": "^0.0.48",
    "@types/lodash": "^4.14.150",
    "@zerollup/ts-transform-paths": "^1.7.17",
    "apollo-server-core": "^2.10.0",
    "apollo-server-express": "^2.10.0",
    "apollo-server-types": "^0.5.1",
    "axios": "^0.20.0",
    "body-parser": "^1.19.0",
    "class-validator": "^0.12.2",
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "express-basic-auth": "^1.2.0",
    "graphql": "^14.7.0",
    "helmet": "^4.1.0",
    "lodash": "^4.17.15",
    "reflect-metadata": "^0.1.10",
    "sqlite3": "^5.0.0",
    "ts-node": "^9.0.0",
    "tsconfig-paths": "^3.9.0",
    "ttypescript": "^1.5.12",
    "type-graphql": "^0.17.6",
    "typeorm": "0.2.25",
    "typescript": "^4.0.2"
},
"scripts": {
    "build": "NODE_ENV=production rm -rf dist/ && ttsc -p tsconfig.prod.json",
    "start": "NODE_ENV=production ts-node dist/server.js",
    "dev": "NODE_ENV=development nodemon",
    "coverage": "NODE_ENV=test yarn test --coverage",
    "test": "HEADLESS=false SLOWMO=50 JEST_PUPPETEER_CONFIG=src/support/puppeteer/jest-puppeteer.config.js yarn run jest --runInBand --config=src/support/jest/jest.integration.config.js",
    "test:unit": "JEST_PUPPETEER_CONFIG=src/support/puppeteer/jest-puppeteer.config.js yarn run jest --runInBand --config=src/support/jest/jest.config.js",
    "test:headless": "JEST_PUPPETEER_CONFIG=src/support/puppeteer/jest-puppeteer.config.js yarn run jest --runInBand",
    "typeorm": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js",
    "seed": "ts-node -r tsconfig-paths/register src/db/seeds.ts",
    "seed:production": "NODE_ENV=production ts-node -r tsconfig-paths/register dist/db/seeds.js"
},
"devDependencies": {
    "@apollo/client": "^3.1.4",
    "@types/expect-puppeteer": "^4.4.0",
    "@types/jest": "^26.0.13",
    "@types/jest-environment-puppeteer": "^4.3.1",
    "@types/node": "^14.6.4",
    "@types/puppeteer": "^3.0.2",
    "@types/react": "^16.9.22",
    "and": "^0.0.3",
    "apollo-client": "^2.6.8",
    "apollo-server-testing": "^2.10.0",
    "apollo-utilities": "^1.3.3",
    "foreman": "^3.0.1",
    "graphql-tag": "^2.10.3",
    "jest": "^26.4.2",
    "jest-cucumber": "^3.0.0",
    "jest-environment-puppeteer": "^4.4.0",
    "jest-puppeteer": "^4.4.0",
    "nock": "^13.0.4",
    "nodemon": "^2.0.2",
    "puppeteer": "^2.1.1",
    "react": "^16.12.0",
    "subscriptions-transport-ws": "^0.9.18",
    "ts-jest": "^26.3.0",
    "typeorm-test-transactions": "^1.10.0"
}
}`)
}
